---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: team-vault-role
spec:
  labelSelector:
    matchExpressions:
      - key: team
        operator: Exists
      - key: environment
        operator: NotIn
        values:
        - build        
  templates:     
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: KubernetesAuthEngineRole
        metadata:
          name: {{ .Labels.team }}-vault-role
          namespace: vault-admin
        spec:
          # Add fields here
          authentication: 
            path: kubernetes
            role: policy-admin
          path: kubernetes
          policies:
            - {{ .Labels.team }}-read-token
          targetNamespaces:
            targetNamespaceSelector:
              matchLabels:
                team: {{ .Labels.team }}
          targetServiceAccounts:
          - default      
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: Policy
        metadata:
          name: {{ .Labels.team }}-read-token
          namespace: vault-admin
        spec:
          # Add fields here
          authentication: 
            path: kubernetes
            role: policy-admin
          policy: |
            # create tokens
            path "/github/token/{{ .Labels.team }}" {
              capabilities = ["read"]
            }
            path "/quay/creds/{{ .Labels.team }}" {
              capabilities = ["read"]
            }
            path "/quay/creds/{{ .Labels.team }}-pusher" {
              capabilities = ["read"]
            }                        
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: QuaySecretEngineRole
        metadata:
          name: {{ .Labels.team }}
          namespace: vault-admin
        spec:
          authentication: 
            path: kubernetes
            role: policy-admin
          path: quay
          namespaceName: raf-backstage-demo
          defaultPermission: read            
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: VaultSecret
        metadata:
          name: quay-pull-secret
          namespace: {{ .Name }}
        spec:
          vaultSecretDefinitions:
          - authentication:
              path: kubernetes
              role: {{ .Labels.team }}-vault-role
              serviceAccount:
                name: default
            name: quaytoken
            path: quay/creds/{{ .Labels.team }}
          output:
            name: quay-pull-secret
            stringData:
              .dockerconfigjson: |
                {"auths":{"quay.io":{"username":"{{ "{{" }} .quaytoken.username {{ "}}" }}","password":"{{ "{{" }} .quaytoken.password {{ "}}" }}","email":"{{ "{{" }} .quaytoken.username {{ "}}" }}@example.com","auth":"{{ "{{" }} list .quaytoken.username ":" .quaytoken.password | join "" | b64enc {{ "}}" }}"}}}
            type: kubernetes.io/dockerconfigjson   
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: team-build-vault-role
spec:
  labelSelector:
    matchExpressions:
      - key: team
        operator: Exists
      - key: environment
        operator: In
        values:
        - build        
  templates: 
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: QuaySecretEngineRole
        metadata:
          name: {{ .Labels.team }}-pusher
          namespace: vault-admin
        spec:
          authentication: 
            path: kubernetes
            role: policy-admin
          path: quay
          namespaceName: raf-backstage-demo
          namespaceType: organization
          defaultPermission: write
          createRepositories: true  
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: VaultSecret
        metadata:
          name: quay-push-secret
          namespace: {{ .Name }}
        spec:
          vaultSecretDefinitions:
          - authentication:
              path: kubernetes
              role: {{ .Labels.team }}-vault-role
              serviceAccount:
                name: default
            name: quaytoken
            path: quay/creds/{{ .Labels.team }}-pusher
          output:
            name: quay-push-secret
            stringData:
              .dockerconfigjson: |
                {"auths":{"quay.io":{"username":"{{ "{{" }} .quaytoken.username {{ "}}" }}","password":"{{ "{{" }} .quaytoken.password {{ "}}" }}","email":"{{ "{{" }} .quaytoken.username {{ "}}" }}@example.com","auth":"{{ "{{" }} list .quaytoken.username ":" .quaytoken.password | join "" | b64enc {{ "}}" }}"}}}
            type: kubernetes.io/dockerconfigjson
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: GitHubSecretEngineRole
        metadata:
          name: {{ .Labels.team }}
          namespace: vault-admin
        spec:
          authentication: 
            path: kubernetes
            role: policy-admin
          path: github
          repositories: []
          permissions: 
            packages: read
            pull_requests: write
            commits: read
    - objectTemplate: |
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: VaultSecret
        metadata:
          name: github-token
          namespace: {{ .Name }}
        spec:
          vaultSecretDefinitions:
          - authentication:
              path: kubernetes
              role: {{ .Labels.team }}-vault-role
              serviceAccount:
                name: default
            name: githubtoken
            path: github/token/{{ .Labels.team }}
          output:
            name: github-pull-secret
            stringData:
              token: "{{ "{{" }} .githubtoken.token {{ "}}" }}"
