apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/raffaelespazzoli/backstage-demo.git
    targetRevision: HEAD
    path: openshift-config/openshift-config
    helm:
      values: | 
        base_domain: "dummy"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-config
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy 